[Doc] Keccak Doc
axiom-crypto/halo2-lib pull request #145
Opened 2023-09-10 20:41 UTC by nyunyunyunyu

2023-09-10 21:56 UTC, jonathanpwang requested changes
Please check for typos throughout.

Also please say a bit more / give an example of the vanilla table format if we only look at the first row per round. (I think having an actual markdown table could be very helpful visually - maybe GPT can just make this.)

And then same example but explaining what happens in the leaf circuit with encoding.

2023-09-10 21:56 UTC, jonathanpwang commented on hashes/zkevm/src/keccak/README.md
> +# ZKEVM Keccka
typo

2023-09-10 21:56 UTC, jonathanpwang commented on hashes/zkevm/src/keccak/README.md
> +The majoir differences is that this version directly represent raw inputs and Keccak results as witnesses, while the original version only has RLCs(random linear combination) of raw inputs and Keccak
typo; please check for typos throughout.

2023-09-10 21:56 UTC, jonathanpwang commented on hashes/zkevm/src/keccak/README.md
> +Keccak circuit in vanilla halo2. This implementation starts from Scroll's version then adopts some changes from [this PR](https://github.com/scroll-tech/zkevm-circuits/pull/216) and [PSE version](htt
this did _not_ start from Scroll's version. Scroll's version is also based on the PSE version, which is due to Brecht. I had the correct attribution here: https://github.com/axiom-crypto/halo2-lib/blob/70c5cc05f8e7e0904533ae4044191dcd16bea214/hashes/zkevm-keccak/src/lib.rs#L2

2023-09-10 21:56 UTC, jonathanpwang commented on hashes/zkevm/src/keccak/README.md
> +Keccak coprocessor circuits and utilities based on Halo2lib.
`halo2-lib`

2023-09-10 21:56 UTC, jonathanpwang commented on hashes/zkevm/src/keccak/README.md
> +- `lookup_key` can be cheaply derived from a bytes input. Specs can be found at `keccak::coprocessor::encode::encode_native_input`. Also `keccak::coprocessor::encode` provides some utilities to encod
`halo2-lib`

2023-09-11 07:35 UTC, nyunyunyunyu commented
> Please check for typos throughout.
> 
> Also please say a bit more / give an example of the vanilla table format if we only look at the first row per round. (I think having an actual markdown table could be very helpful visually - maybe GPT can just make this.)
> 
> And then same example but explaining what happens in the leaf circuit with encoding.

GPT is pretty useful! It helped me correct typos and generate the prototype of the table

2023-09-11 08:40 UTC, jonathanpwang reviewed
Very nice tables! I think this will be very helpful.

One last question: is `is_final` actually 1 on the first 17 rows in the table?
From
```
is_final: is_final_block && round == NUM_ROUNDS && row_idx == 0,
```
I actually thought it was only going to be nonzero on row 250.

2023-09-11 16:53 UTC, nyunyunyunyu commented
> Very nice tables! I think this will be very helpful.
> 
> One last question: is `is_final` actually 1 on the first 17 rows in the table? From
> 
> ```
> is_final: is_final_block && round == NUM_ROUNDS && row_idx == 0,
> ```
> 
> I actually thought it was only going to be nonzero on row 250.

My understanding on is_final was inaccurate. Corrected the description.

2023-09-11 17:51 UTC, merged