[feat] Add bitwise rotate operators for const bits
axiom-crypto/halo2-lib pull request #55
Opened 2023-05-23 06:36 UTC by nyunyunyunyu

- Add `const_right_rotate_unsafe` and `const_left_rotate_unsafe` into `GateInstructions`. 
- These functions can bitwise left/rotate rotate a unsigned integer by a const bit.
- These functions don't do range checking so it's unsafe.

2023-05-24 19:00 UTC, jonathanpwang requested changes
Some questions about shift indices, otherwise looks good.

Can you also please run `rustfmt` on all docs?

You can do this automatically in vscode with setting:
```
  "editor.formatOnSave": true,
```

2023-05-24 19:01 UTC, jonathanpwang commented
Also please fix merge issues (merge community-edition updates)

2023-05-27 05:45 UTC, nyunyunyunyu commented on halo2-base/src/gates/flex_gate.rs
> +            Constant(self.pow_of_two()[num_bits - bit + 1]),
Yes you are right. It was a dumb bug :(

2023-05-27 05:46 UTC, nyunyunyunyu commented on halo2-base/src/gates/tests/bitwise_rotate.rs
> +    test_bitwise_rotate_gen::<1, 10>(8, false, 1, 1024, true);
It was a dumb bug :( Fixed

2023-05-27 06:03 UTC, nyunyunyunyu commented
@PatStiles @jonathanpwang I think the naming in [halo2-base/src/gates/tests](https://github.com/axiom-crypto/halo2-lib/tree/community-edition/halo2-base/src/gates/tests) is inconsistent. Are you good if I:
1. Remove all "_test" suffixes? It's redundant because the folder name already contains "tests"
2. For testing utility functions(e.g. `tests_ground_truth.rs`), move all of them into `mod.rs` or `testing_utils.rs`?

2023-05-27 07:40 UTC, jonathanpwang approved these changes
LGTM!

2023-05-27 07:40 UTC, jonathanpwang approved these changes
LGTM!

2023-05-27 07:41 UTC, jonathanpwang commented
> @PatStiles @jonathanpwang I think the naming in [halo2-base/src/gates/tests](https://github.com/axiom-crypto/halo2-lib/tree/community-edition/halo2-base/src/gates/tests) is inconsistent. Are you good if I:
> 
> 1. Remove all "_test" suffixes? It's redundant because the folder name already contains "tests"
> 2. For testing utility functions(e.g. `tests_ground_truth.rs`), move all of them into `mod.rs` or `testing_utils.rs`?

1. Sounds good
2. Sure, `testing_utils.rs` or just `utils.rs` are good.

2023-05-28 05:30 UTC, nyunyunyunyu commented
> > @PatStiles @jonathanpwang I think the naming in [halo2-base/src/gates/tests](https://github.com/axiom-crypto/halo2-lib/tree/community-edition/halo2-base/src/gates/tests) is inconsistent. Are you good if I:
> > 
> > 1. Remove all "_test" suffixes? It's redundant because the folder name already contains "tests"
> > 2. For testing utility functions(e.g. `tests_ground_truth.rs`), move all of them into `mod.rs` or `testing_utils.rs`?
> 
> 1. Sounds good
> 2. Sure, `testing_utils.rs` or just `utils.rs` are good.

Great! I will do it in a sperate PR. 
I saw test bn254::tests::fixed_base_msm::bench_fixed_base_msm failed. I believe this PR doesn't touch halo2_ecc. Is the test flaky?

2023-05-28 09:02 UTC, jonathanpwang commented
> > > @PatStiles @jonathanpwang I think the naming in [halo2-base/src/gates/tests](https://github.com/axiom-crypto/halo2-lib/tree/community-edition/halo2-base/src/gates/tests) is inconsistent. Are you good if I:
> > > 
> > > 1. Remove all "_test" suffixes? It's redundant because the folder name already contains "tests"
> > > 2. For testing utility functions(e.g. `tests_ground_truth.rs`), move all of them into `mod.rs` or `testing_utils.rs`?
> > 
> > 
> > 
> > 1. Sounds good
> > 2. Sure, `testing_utils.rs` or just `utils.rs` are good.
> 
> Great! I will do it in a sperate PR. I saw test bn254::tests::fixed_base_msm::bench_fixed_base_msm failed. I believe this PR doesn't touch halo2_ecc. Is the test flaky?

Yes I had to fix a typo: https://github.com/axiom-crypto/halo2-lib/commit/0b18ef13c69f21f6509f41e69bdcf047f0a8fedb

2023-05-28 09:03 UTC, merged